# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('channel', models.CharField(max_length=300, null=True)),
                ('country', models.CharField(max_length=300, null=True)),
                ('os', models.CharField(max_length=300, null=True)),
                ('impressions', models.CharField(max_length=300, null=True)),
                ('clicks', models.CharField(max_length=300, null=True)),
                ('installs', models.CharField(max_length=300, null=True)),
                ('spend', models.CharField(max_length=300, null=True)),
                ('revenue', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
