# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-15 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20190914_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
    ]
